name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up uv
        uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4 # v6.7.0

      - name: Sync dependencies
        run: uv sync --all-extras --python ${{ matrix.python-version }}

      - name: Run linters
        run: uv run -- ruff check .

      - name: Run type checks
        run: uv run -- mypy scripts

      - name: Run tests
        env:
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
        run: uv run -- python -m pytest --cov=scripts

      - name: Upload coverage report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage-${{ matrix.python-version }}
          path: |
            coverage.xml
            htmlcov

      - name: Upload pytest results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: .pytest_cache
