name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up uv
        uses: astral-sh/setup-uv@2c8613df47424ecdeb54fa0dc0c479bc296e50b6 # v1.2.0

      - name: Build distribution
        run: uv build

      - name: Compute checksums
        run: |
          cd dist
          shasum -a 256 -- * > SHA256SUMS

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
        with:
          files: |
            dist/*
            dist/SHA256SUMS

      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: dist-artifacts
          path: dist
